// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {vpn} from '../models';

export function CreateNetwork(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetConfig():Promise<config.Config>;

export function GetNetworkStatus():Promise<Record<string, any>>;

export function GetPeers():Promise<Array<vpn.PeerInfo>>;

export function JoinNetwork(arg1:string,arg2:string):Promise<Record<string, any>>;

export function LeaveNetwork():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SendTestPing(arg1:string):Promise<string>;

export function ShowError(arg1:string):Promise<void>;

export function ShowInfo(arg1:string,arg2:string):Promise<void>;

export function TestServerConnection(arg1:string):Promise<Record<string, any>>;
