// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNetwork(arg1, arg2) {
  return window['go']['app']['App']['CreateNetwork'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetNetworkStatus() {
  return window['go']['app']['App']['GetNetworkStatus']();
}

export function GetPeers() {
  return window['go']['app']['App']['GetPeers']();
}

export function JoinNetwork(arg1, arg2) {
  return window['go']['app']['App']['JoinNetwork'](arg1, arg2);
}

export function LeaveNetwork() {
  return window['go']['app']['App']['LeaveNetwork']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SendTestPing(arg1) {
  return window['go']['app']['App']['SendTestPing'](arg1);
}

export function ShowError(arg1) {
  return window['go']['app']['App']['ShowError'](arg1);
}

export function ShowInfo(arg1, arg2) {
  return window['go']['app']['App']['ShowInfo'](arg1, arg2);
}

export function TestServerConnection(arg1) {
  return window['go']['app']['App']['TestServerConnection'](arg1);
}
